### ISSUE TITLE
我想找一种优秀的调试方式，不知道是否可以实现

### ISSUE THREAD

**Issue by shangxinbo** [CordovaCn/CordovaCn#4]
调试cordova要先编译后运行，我想找一种和web开发调试类似的方式，快速并且实时，这样开发效率会大大提高，但是我想到android和ios上app的运行原理，现在在思考这种想法能不能实现

**Comment by ryouaki** [comment]
你是指调试的时候，修改代码到反应到程序上是实时同步？像在inspect里面修改css那样？

**Comment by shangxinbo** [comment]
@ryouaki  是这个意思，尽量实时的方法

**Comment by ryouaki** [comment]
目前JS代码好像也没能达到这个地步吧？只有html和css可以这样，至于android和ios平台上更不可能了，毕竟代码需要编译，除非哪个技术实力雄厚的IT企业开发出一个虚拟机，直接可以根据代码来虚拟出程序运行结果。

**Comment by code-L** [comment]
是有的，GapDebug 和PhoneGap Developer App

**Comment by shangxinbo** [comment]
@code-L 我以前用过这个东西，前两天再拿出来就不管用了，我看你的语气也不像是正在用这个，所以为什么有这东西大家都不用呢，我一直在找这个原因

**Comment by ryouaki** [comment]
[weinre](http://blog.csdn.net/dojotoolkit/article/details/6280924)  这个玩意 好像可以达到你的要求，但是以前我用的时候不太好用

**Comment by code-L** [comment]
@ShangXinbo 是的，我只用过后者，前者只是听别人介绍过，我使用的时候，功能上不是特别完善，有的时候会出现与代码不一致的情况。（快有1年没用了，现在什么样子不清楚）

**Comment by ryouaki** [comment]
close
